name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_URL: ${{ secrets.PROJECT_URL }}
      SERVICE_ROLE_KEY: ${{ secrets.SERVICE_ROLE_KEY }}
      ANON_KEY: ${{ secrets.ANON_KEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: |
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs
          npm install -g supabase

      - name: Deploy functions
        run: |
          supabase login --service-role $SERVICE_ROLE_KEY
          supabase functions deploy contact --project-ref $PROJECT_URL
